baseURL = "https://sebastiandedeyne.com"
languageCode = "en-us"
title = "Seb De Deyne"

summaryLength = 1_000_000
rssLimit = 10
paginate = 15

[taxonomies]
  tags = "tags"

[permalinks]
  posts = "/:slug"
  links = "/links/:slug"

[author]
  name = "Seb De Deyne"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    ordered = true
