baseURL = "https://sebastiandedeyne.com"
languageCode = "en-us"
title = "Sebastian De Deyne"

summaryLength = 1_000_000
rssLimit = 10
enableGitInfo = true
paginate = 20

[taxonomies]
  category = "categories"

[permalinks]
  posts = "/:slug"
  categories = "/:title"

[author]
  name = "Sebastian De Deyne"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    ordered = true
