baseURL = "https://sebastiandedeyne.com"
languageCode = "en-us"
title = "Seb De Deyne"

summaryLength = 1_000_000
rssLimit = 10
enableGitInfo = true
paginate = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:slug"
  categories = "/:title"
  tags = "/tags/:title"

[author]
  name = "Seb De Deyne"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    ordered = true
